// frontend/src/pages/Catalog.vue
<template>
	<div class="font-sans min-h-screen flex flex-col relative">
		<div class="h-1 bg-green"></div>
		<the-header :link-inactive="'green'" :link-active="'green-dark'"></the-header>
		<main class="flex flex-1 mx-auto">
			<div class="mt-8 px-1 sm:px-4 md:px-8">
				<transition name="fade-slow">
					<div v-if="tracks !== undefined && tracks.length > 0">
						<track-catalog :tracks="tracks" ref="trackCatalog"></track-catalog>
						<div v-if="isLoadingTracks" class="w-full flex flex-col justify-center items-center text-grey mt-6 mb-12">
							<line-scale-pulse-out-rapid-loader size="50px" color="#B8C2CC"></line-scale-pulse-out-rapid-loader>
							More tracks are loading
						</div>
					</div>
					<div v-else class="fixed pin-x flex flex-col justify-center items-center text-grey" style="top: 40vh">
						<div v-if="errorMessage === ''" class="flex flex-1 w-full justify-center items-center">
							<line-scale-pulse-out-rapid-loader size="50px" color="#B8C2CC"></line-scale-pulse-out-rapid-loader>
						</div>
						<p class="mt-6 text-2xl-responsive">
							<template v-if="errorMessage === ''">
								The catalog is loading
							</template>
							<template v-else>
								{{ errorMessage }}
							</template>
						</p>
					</div>
				</transition>
			</div>
		</main>
		<div class="h-1 bg-green"></div>
	</div>
</template>

<script lang="ts">
	import Vue from "vue"
	import request from "graphql-request"
	import TheHeader from "../components/TheHeader.vue"
	import TrackCatalog from '../components/TrackCatalog.vue'
	
	import 'vue-loaders/dist/vue-loaders.css'
	// @ts-ignore
	import {LineScalePulseOutRapidLoader} from 'vue-loaders';
	
	import "../../tailwind.postcss"
	
	let tracksFragment = `
		date {
			year
			monthName: month_name
			day
		}
		id
		name
		artist
		recordLabel: record_label
		image
		subgenresWithTailwindColorsJSON: subgenres_flat_json(and_colors: TAILWIND)
		subgenresWithHexColorsJSON: subgenres_flat_json(and_colors: HEX)
	`
	
	
	export default Vue.extend({
		components: {
			LineScalePulseOutRapidLoader,
			TheHeader,
			TrackCatalog,
		},
		created(): void {
			window.addEventListener('scroll', this.scrolled);
			
			(this as any).isLoadingTracks = true
			request("https://genre.guide/graphql", `
				{
					tracks {
						${tracksFragment}
					}
				}
			`).then((data: Object): void => {
				((data as any).tracks as object[]).forEach((track, index) => {
					(track as any).transitionIndex = index;
					(this as any).tracks.push(track);
				});
				
				(this as any).isLoadingTracks = false
				// Don't ask questions
				let component = this;
				setTimeout(function () {
					(component.$refs.trackCatalog as any).updateTracks((data as any).tracks.length)
				}, 0);
			}).catch(error => {
				if (error instanceof TypeError && error.message.startsWith("NetworkError")) {
					(this as any).errorMessage = "There was a network error trying to load the catalog"
				} else if (error.hasOwnProperty("response") && error.response!.errors.length > 0) {
					(this as any).errorMessage = "There was an error in the catalog response itself, which is probably out of your control"
				} else {
					(this as any).errorMessage = "An unknown error occurred loading the catalog. If you understand JavaScript, see the developer console"
				}
				
				(window as any).catalogError = error
				console.log("The error encountered can be inspected here by referring to it as catalogError (a property of the window object):")
				console.log(error.message)
			})
		},
		data(): Object {
			return {
				isLoadingTracks: true,
				tracks: [] as string[],
				errorMessage: ""
			}
		},
		destroyed() {
			window.addEventListener('scroll', this.scrolled);
		},
		methods: {
			loadMoreTracks(): void {
				(this as any).isLoadingTracks = true
				
				request("https://genre.guide/graphql", `
					query tracksFromBeforeTheLastTrackCurrentlyInTheCatalog($beforeID: ID!) {
						tracks(before_id: $beforeID) {
							${tracksFragment}
						}
					}
				`, {
					beforeID: (this as any).tracks[(this as any).tracks.length - 1].id
				}).then((data: Object) => {
					((data as any).tracks as object[]).forEach((track: any, index: number): void => {
						track.transitionIndex = index;
						(this as any).tracks.push(track);
					});
					(this as any).isLoadingTracks = false;
					(this.$refs.trackCatalog as any).updateTracks((data as any).tracks.length);
				})
			},
			scrolled(event: Event): void {
				if ((3 * window.innerHeight + window.scrollY) >= document.body.offsetHeight) {
					if (!(this as any).isLoadingTracks) {
						(this as any).loadMoreTracks()
					}
				}
			},
		},
	})
</script>

<style>
	.fade-slow-enter-active, .fade-slow-leave-active {
		transition: opacity 400ms ease-in;
	}
	
	.fade-slow-enter, .fade-slow-leave-to {
		transition: opacity 200ms ease-out;
		opacity: 0;
	}
</style>

// frontend/src/routes/catalog.svelte
<script>
  import { get } from "svelte/store";
  import { sineIn } from "svelte/easing";
  import { fade } from "svelte/transition";
  import fetch from "node-fetch";
  import ApolloClient from "apollo-boost";
  import { query } from "svelte-apollo";
  import { FrownIcon } from "svelte-feather-icons";
  import { GET_MOST_RECENT_TRACKS, getTracksBefore } from "../queries";
  import { siteName } from "../stores";
  import TrackCatalog from "../components/TrackCatalog.svelte";

  const client = new ApolloClient({
    uri: "https://genre.guide/graphql",
    fetch
  });

  let innerHeight, scrollY;

  let tracks = [];
  let isLoadingTracks;

  const loadTracks = () => {
    if (isLoadingTracks) return;
    isLoadingTracks = true;

    let tracksRequestStore;
    let initialTrackLoad;

    if (tracks.length == 0) {
      tracksRequestStore = query(client, { query: GET_MOST_RECENT_TRACKS });
      // This is a promise so it can make the await block in the HTML work
      initialTrackLoad = new Promise((resolve, reject) =>
        tracksRequestStore.subscribe(tracksRequest =>
          tracksRequest.then(tracksResponse => resolve(undefined))
        )
      );
    } else {
      tracksRequestStore = query(client, {
        query: getTracksBefore(tracks[tracks.length - 1].id)
      });
    }

    tracksRequestStore.subscribe(tracksRequest =>
      tracksRequest.then(({ data: { tracks: newTracks } }) => {
        newTracks.forEach((track, loadIndex) => {
          track.loadIndex = loadIndex;
        });

        tracks = [...tracks, ...newTracks];
        isLoadingTracks = false;
      })
    );

    return initialTrackLoad;
  };

  const initialTrackLoad = loadTracks();
</script>

<style>
  /* https://github.com/ConnorAtherton/loaders.css */
  @keyframes line-scale-pulse-out-rapid {
    0%,
    100% {
      height: 6rem;
    }
    80% {
      height: 1rem;
    }
  }
  .line-scale-pulse-out-rapid > div {
    animation-fill-mode: both;
    display: inline-block;
    vertical-align: middle;
    animation: line-scale-pulse-out-rapid 0.9s 0s infinite
      cubic-bezier(0.11, 0.49, 0.38, 0.78);
  }
  .line-scale-pulse-out-rapid > div:nth-child(2),
  .line-scale-pulse-out-rapid > div:nth-child(4) {
    animation-delay: -0.25s !important;
  }
  .line-scale-pulse-out-rapid > div:nth-child(1),
  .line-scale-pulse-out-rapid > div:nth-child(5) {
    animation-delay: -0.5s !important;
  }
</style>

<svelte:head>
  <title>Catalog - {$siteName}</title>
</svelte:head>

<svelte:window
  bind:scrollY
  bind:innerHeight
  on:scroll|passive={() => {
    if (innerHeight * 3 + scrollY > document.body.offsetHeight) loadTracks();
  }} />
<svelte:body bind:offsetHeight />

<div
  in:fade={{ duration: 1250 }}
  class="flex flex-col flex-1 items-center justify-center px-8">
  {#await initialTrackLoad}
    <div class="flex flex-1 items-center justify-center my-4">
      <div class="line-scale-pulse-out-rapid h-24 flex items-center">
        <!-- This particular loader needs 5 children -->
        {#each Array(5) as _}
          <div
            class="theme-light:bg-gray-400 theme-dark:bg-gray-600 rounded-full
            mx-1 w-2" />
        {/each}
      </div>
    </div>
  {:then}
    <TrackCatalog {tracks} />
    <div class="flex flex-1 items-center justify-center my-4">
      <div class="line-scale-pulse-out-rapid h-24 flex items-center">
        {#each Array(5) as _}
          <div
            class="theme-light:bg-gray-400 theme-dark:bg-gray-600 rounded-full
            mx-1 w-2" />
        {/each}
      </div>
    </div>
  {:catch error}
    <div
      class="flex flex-col items-center text-lg theme-light:text-gray-500
      theme-dark:text-gray-600">
      <div class="w-6 h-6">
        <FrownIcon />
      </div>
      <span>
        {#if error.message === 'Network error: NetworkError when attempting to fetch resource.'}
          There was a network error caused by trying to load the catalog
        {:else if error.graphQLErrors !== undefined && error.graphQLErrors.length > 0}
          There was an error in the catalog response, which is probably out of
          your control
        {:else}
          {console.log(error) || console.log(Object.entries(error)) || 'An unknown error occurred loading the catalog. If you understand JavaScript, see the developer console to inspect what went wrong'}
        {/if}
      </span>
    </div>
  {/await}
</div>
